version: "2"
services:
  resilio:
    image: amaya382/resilio:latest
    ports:
      - "8080:80"
    volumes:
      - "./rslsync.conf:/etc/rslsync.conf"
      - "./rslsync.log:/var/log/rslsync.log"
      - "./settings/:/settings/"
      - "/path/to/sync/root/:/resilio/"
    restart: always
